spring.application.name=urlshortener2

spring.datasource.url=jdbc:postgresql://dpg-d9j7rhsvikkc73djqd1g-a:5432/saplinks-db
spring.datasource.username=saplinks_db_user
spring.datasource.password=GroP3sozeG4vQ1NNFg2n02H3nlSAZGzQ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}